Repository frequenz-floss/frequenz-client-microgrid-python, pull requests merged in 2024-03, with the labels that each got.

#17 Use streaming helper and retry strategies from `frequenz-client-base`
  mkdocs.yml
  pyproject.toml
  src/frequenz/client/microgrid/__init__.py
  src/frequenz/client/microgrid/_client.py
  src/frequenz/client/microgrid/_retry.py
  tests/test_client.py
  tests/test_retry.py
Labels: cmd:skip-release-notes, part:tests, part:tooling, part:client

#20 Upgrade `client-base` to v0.2.0
  RELEASE_NOTES.md
  mkdocs.yml
  pyproject.toml
  src/frequenz/client/microgrid/__init__.py
  src/frequenz/client/microgrid/_client.py
  tests/test_client.py
Labels: part:docs, part:tests, part:tooling, part:client

#21 Clear release notes
  RELEASE_NOTES.md
Labels: part:docs

#22 Expose missing symbols
  RELEASE_NOTES.md
  src/frequenz/client/microgrid/__init__.py
  src/frequenz/client/microgrid/_constants.py
Labels: part:docs, part:client

#23 Clear release notes
  RELEASE_NOTES.md
Labels: part:docs

#24 Downgrade protobuf to 4.21.6
  .github/workflows/ci.yaml
  RELEASE_NOTES.md
  pyproject.toml
Labels: part:docs, part:tooling

#25 Clear release notes
  RELEASE_NOTES.md
Labels: part:docs

#26 Update minimum `frequenz-channels` version to `v1.0.0-rc1`
  RELEASE_NOTES.md
  pyproject.toml
Labels: part:docs, part:tooling

#27 Clear RELEASE_NOTES.md
  RELEASE_NOTES.md
Labels: part:docs

#30 Add reactive power for inverters, meters and EV chargers
  README.md
  RELEASE_NOTES.md
  src/frequenz/client/microgrid/_component.py
  src/frequenz/client/microgrid/_component_data.py
  tests/test_component_data.py
Labels: part:docs, part:tests, part:client

#29 Improve Location docs and tests
  src/frequenz/client/microgrid/_metadata.py
  tests/test_metadata.py
Labels: cmd:skip-release-notes, part:docs, part:tests, type:enhancement

#32 Clear release notes
  RELEASE_NOTES.md
Labels: part:docs, type:tech-debt
