Repository frequenz-floss/frequenz-client-microgrid-python, pull requests merged in 2025-02, with the labels that each got.

#115 Revert "Enable autorefs plugin option to resolve closest references"
  mkdocs.yml
Labels: part:tooling, type:tech-debt

#116 Widen `frequenz-client-base` dependency to allow `v0.9.0`
  RELEASE_NOTES.md
  pyproject.toml
Labels: part:docs, part:tooling

#117 Clear release notes
  RELEASE_NOTES.md
Labels: part:docs
